name: Extração de Secrets

on:
  workflow_dispatch:

jobs:
  export-env:
    runs-on: ubuntu-latest

    steps:
      - name: Instala gh cli
        run: |
          sudo apt install gh -y          
          
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Acessar secrets individualmente
        run: |
          echo "======="
          echo -n "SECRET_105 Size:"
          echo "${{ secrets.SECRET_105 }}" | wc
          if [ "${{ secrets.SECRET_105 }}" == "Teltec@123" ]; then echo "Valor so SECRET_105 acessado com sucesso!" ; fi   
          echo "======="
          echo -n "SECRET_088 Size:"
          echo "${{ secrets.SECRET_088 }}" | wc
          if [ "${{ secrets.SECRET_088 }}" == "Teltec@123" ]; then echo "Valor so SECRET_088 acessado com sucesso!" ; fi
          echo "======="
          
      - name: Exportar secrets com gh cli
        run: |
          echo "${{ secrets.GHTOKEN }}" | gh auth login --with-token
          gh auth status
          gh secret list --org teltecdevops | cut -f 1 | tr -d " " | tr -d "\t" >> .env
          cat .env

      - name: Copiar arquivo de segredos
        run: cp -v .env env_vars_export.txt      
        
      - name: Verificar conteúdo do arquivo (debug)
        run: |
          echo "Arquivo criado com sucesso:"
          ls -la .env* *.txt
