name: Extração de Variáveis de Ambiente

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  export-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Exportar variáveis de ambiente
        uses: 0ndt/envfile@v2
        with:
          secrets: ${{ toJSON(secrets) }}
          file: .env.secrets

      - name: Verificar conteúdo do arquivo (debug)
        run: |
          echo "Arquivo criado com sucesso:"
          ls -la .env.secrets

      - name: Copiar arquivo de segredos
        run: cp -v .env.secrets env_vars_export.txt

      - name: Upload do arquivo como artefato
        uses: actions/upload-artifact@v4
        with:
          name: Variaveis_Ambiente
          path: env_vars_export.txt
          retention-days: 5  # Define período de retenção do artefato